### ISSUE TITLE
Are there any Debuggers for TypeScript?

### ISSUE THREAD

**Issue by KaanBaylan** [rstropek-teaching/real-time-game-quiz-4ahif-KaanBaylan#1]
i have a problem with my game, where i dont know if it counts a certain counter.

I wanted to know if there are some Debugger-Programms or Websites you could suggest me.

**Comment by rstropek** [comment]
Hi @KaanBaylan 

I saw that you created two issues with questions and closed them already. Problems solved? If you habe problems where you think I could help, let me know.

Greetings,
Rainer Stropek.

**Comment by KaanBaylan** [comment]
Yeah I found solutions myself
