### ISSUE TITLE
Uncaught ReferenceError exports is not defined

### ISSUE THREAD

**Issue by KaanBaylan** [rstropek-teaching/real-time-game-quiz-4ahif-KaanBaylan#3]
When I start the game (node server.js) i come to my Login Page, but cant do anything in the console it says

Uncaught ReferenceError exports is not defined main.js:2

if I delete the code there:
Object.defineProperty(exports, "__esModule", { value: true });

it works perfectly fine.

Can you please help me solve this problem?

**Comment by rstropek** [comment]
Hi @KaanBaylan 

Good question, unfortunately there is no simple answer. You added imports (e.g. `import { text } from "body-parser"`) to *main.ts*. This code would work like a charm if it were running on the server-side (in Node.js). In your case, the code is running on the client-side (in the browser). Browsers do not understand `import` yet (to be more specific: [Recent versions of Chrome do](https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7) but you cannot expect module-support in browsers today).

If you want to use modules on the client-side, you have three options:

* Use a loader like [system.js](https://github.com/systemjs/systemjs)
* Use a bundler like [webpack](https://webpack.js.org/concepts/)
* Require the use of a rather new Chrome version and follow the [guidelines for ES6 modules in Chrome](https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7)

I looked at your code and I am not sure why you need the `import` at all. Wouldn't it be possible to just remove it? That would be a very simple solution for the problem. In that case you would not need a bundler.

Hope this helps.

Greetings,
Rainer Stropek.

**Comment by KaanBaylan** [comment]
It works when I delete it 👍

Thank You! 
I dont know why i wrote it and thought it was something i needed anyway and didn't delete it therefor
 🤔
