### ISSUE TITLE
Can I use pictures from the Web?

### ISSUE THREAD

**Issue by KaanBaylan** [rstropek-teaching/real-time-game-quiz-4ahif-KaanBaylan#4]
Can I take some Pictures from the Internet as my hero picture?

or do i have to create them myself?

**Comment by rstropek** [comment]
Of course you can. Strictly speaking, you need to make sure that the image you take is *Creative Commons*. You can use [Google](https://support.google.com/websearch/answer/29508?hl=de) to search for free images using special filters.

Hope this helps,
Rainer Stropek.
