### ISSUE TITLE
Mobile rotate 

### ISSUE THREAD

**Issue by KaanBaylan** [rstropek-teaching/real-time-game-quiz-4ahif-KaanBaylan#5]
is there a way to see if the Mobile User is holding his phone verticaly or horizontaly?

Because the game should only be visible if the phone is horizontal

**Comment by KaanBaylan** [comment]
![example](https://user-images.githubusercontent.com/31959300/34607993-6fa91f44-f216-11e7-879f-cc0a0e808987.PNG)

**Comment by rstropek** [comment]
One of the simplest ways to detect the orientation is to compare windows width and height. Take a look at [this sample](https://codepen.io/adamrifai/pen/aOdOrz). Hope that helps.

Greetings,
Rainer Stropek.
