### ISSUE TITLE
My Game isn't complete :(

### ISSUE THREAD

**Issue by KaanBaylan** [rstropek-teaching/real-time-game-quiz-4ahif-KaanBaylan#6]
I have underestimated the game and so therefore a lot of things do not work:

- Only working mode is the 1v1 mode
- There are no different lobbys
- There isn't a economy system
- I don't use phaser (in my opinion it has too much (Gravitation etc. i dont need any of those))
- There are no actions as listed in my Wiki
- The game isn't mobile friendly

What works:
- The 1v1 mode works completely
- 6 different heroes with all having one passive ability and one special ability (all of them are diffrent)
- Guessing Game 

I am sorry, that i havent thought long about my game ._.
I hope it is not a big problem, that I am not finished :(

**Comment by rstropek** [comment]
Absolutely no problem. What you achieved is impressive. The homework's goal was that you practice - and you definitely did that.

Greetings,
Rainer Stropek.
